pipeline {
    agent { label 'master' }
	
parameters {
    string( name: 'war_ver',
            defaultValue: '2.0.0',
            description: 'Release number' )
            
    string( name: 'NEXUS_IP',
            defaultValue: '172.31.35.191',
            description: 'Nexus IP' )        
            
    string( name: 'DOCKER_USERNAME',
            defaultValue: 'nixvipin',
            description: 'Docker Username' )        
  }
  
    stages {
	    stage('DockerDockerRepo') {
            steps {
                sh "git clone https://github.com/nixvipin/myprod.git \$WORKSPACE/myprod"
            }
		}
	    stage('DockerImageDelete') {
            steps {
                sh  "docker rmi \$(docker images -q) -f || date"
		    }
	    }
	    stage('DockerImageBuild') {
            steps {
                sh "echo ${params.DOCKER_USERNAME}"
                sh  "docker build --build-arg war_ver=${params.war_ver} --build-arg NEXUS_IP=${params.NEXUS_IP} -t ${params.DOCKER_USERNAME}/mytomcat -f \$WORKSPACE/myprod/app/Dockerfile ."           
		    }
	    }
    }    
}
