pipeline {
    agent { label 'master' }
	
parameters {
    string( name: 'war_ver',
            defaultValue: '${REL_VERSION}',
            description: 'Release number' )
    string( name: 'NEXUS_IP',
            defaultValue: '${NEXUS_IP}',
            description: 'Nexus IP' )        
    string( name: 'DOCKER_USERNAME',
            defaultValue: '${DOCKER_USERNAME}',
            description: 'Docker Username' )        
    string( name: 'TAG_NAME',
            defaultValue: '${TAG_NAME}',
            description: 'Docker Username' )        
  }
  
    stages {
	    stage('DockerDockerRepo') {
            steps {
                sh  "rm -rf myprod"
                sh "git clone https://github.com/nixvipin/myprod.git \$WORKSPACE/myprod"
            }
		}
	    stage('DockerImageDelete') {
            steps {
                sh  "docker rmi \$(docker images -q) -f || date"
		    }
	    }
	    stage('DockerImageBuild') {
            steps {
                sh  "docker build --build-arg war_ver=${params.war_ver} --build-arg NEXUS_IP=${params.NEXUS_IP} -t ${params.DOCKER_USERNAME}/mytomcat:${params.TAG_NAME} -f \$WORKSPACE/myprod/app/Dockerfile ."           
		    }
	    }
	    stage('DockerImagePush') {
            steps {
                sh  "docker image push ${params.DOCKER_USERNAME}/mytomcat:${params.TAG_NAME}"
		    }
	    }
    }    
}
